version: "3.2"
services:
  frontend:
    container_name: application
    ports:
      - 5173:5173      
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    env_file:
      - .env      
  
  backend:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env      
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/

  mysql:
    container_name: mysqldev           
    image: mysql:5.7
    env_file:
      - .env  
    environment:
      MYSQL_HOST: $DB_HOST
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 3306
    restart: unless-stopped     
    volumes:
      - ./db:/docker-entrypoint-initdb.d/       

  phpmyadmin:
    container_name: phpmyadmindev  
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 5427:80
    restart: always      